<?php
namespace Modules\Language\Models;

use App\BaseModel;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\App;

class Language extends BaseModel
{
    use SoftDeletes;
    protected $table = 'core_languages';
    protected $fillable = [
        'locale',
        'name',
        'active',
        'flag',
        'status',
        'is_default',
        'is_rtl',
    ];

    public function getTranslatedNumberAttribute()
    {
        $count = Translation::where('locale', $this->locale)->whereRaw(" IFNULL(string,'') != '' ")->count();
        return $count;
    }

    public static function getActive($withCurrent = true)
    {
        $key = 'locale_active_' . ((int) $withCurrent);
        if (Cache::has($key)) {
            return Cache::get($key);
        }
        try {
            $q = parent::query();
            if(!$withCurrent){
                $q->where('locale', '!=', App::getLocale());
            }
            $value = $q->where('status', 'publish')->orderByRaw('CASE WHEN (locale = \'' . e(setting_item('site_locale')) . '\') THEN 0 ELSE 1 END')->get();
            Cache::forever($key, $value);
            return $value;
        } catch (\Exception $e) {
            Log::warning("Language::getActive connection failed: " . $e->getMessage());
            return collect([]);
        }
    }

    public static function findByLocale($locale){
        $key = 'locale_' . $locale;
        if (Cache::has($key)) {
            return Cache::get($key);
        }
        try {
            $value = Language::where('locale', $locale)->first();
            Cache::forever($key, $value);
            return $value;
        } catch (\Exception $e) {
            Log::warning("Language::findByLocale connection failed: " . $e->getMessage());
            return null;
        }
    }

    public function save(array $options = [])
    {
        $res =  parent::save($options); // TODO: Change the autogenerated stub

        if($res){
            Cache::forget('locale_' . $this->locale);
            Cache::forget('locale_active_0');
            Cache::forget('locale_active_1');
        }

        return $res;
    }

    public function delete()
    {
        $locale = $this->locale;

        $res = parent::delete(); // TODO: Change the autogenerated stub

        if($res){
            Cache::forget('locale_' . $locale);
            Cache::forget('locale_active_0');
            Cache::forget('locale_active_1');
        }

        return $res;
    }

    public function update(array $attributes = [], array $options = [])
    {
        $old = $this->locale;

        $res =  parent::update($attributes, $options); // TODO: Change the autogenerated stub

        if($res){
            Cache::forget('locale_' . $old);
            if($old != $this->locale){
                Cache::forget('locale_' . $this->locale);
            }
            Cache::forget('locale_active_0');
            Cache::forget('locale_active_1');
        }

        return $res;

    }
}