<?php
namespace Modules\Core\Models;

use App\BaseModel;

class SEO extends BaseModel
{
    protected $table = 'bc_seo';
    protected $fillable = [
        'seo_index',
        'seo_title',
        'seo_desc',
        'seo_image',
        'seo_share',
        // Extended for per-locale OG / Twitter overrides (admin can translate them
        // separately from the origin tour row's og_title / twitter_title columns).
        'seo_keywords',
        'og_title',
        'og_description',
        'twitter_title',
        'twitter_description',
    ];

    protected $casts = [
        'seo_share'  => 'array',
    ];

    public function fill(array $attributes)
    {
        if(!empty($attributes)){
            foreach ( $this->fillable as $item ){
                $attributes[$item] = $attributes[$item] ?? null;
            }
        }
        return parent::fill($attributes); // TODO: Change the autogenerated stub
    }

}
